language: node_js
node_js:
  - "12"
services:
  - docker
script:
  - npm install -g serverless@1.74.1
  - npm run test || travis_terminate 1
  - docker-compose -f testdata/docker-compose.yml up -d
  - npm run integration-test || travis_terminate 1
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ] && [ "$TRAVIS_BRANCH" = "master" ]; then npm run deploy-prod; fi
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ] && [ "$TRAVIS_BRANCH" = "develop" ]; then npm run deploy-dev; fi
branches:
  only:
  - master
  - develop